export type Stack =
  | "HTML"
  | "CSS"
  | "JavaScript"
  | "React"
  | "React.js"
  | "React Router"
  | "TanStack Router"
  | "Vite"
  | "Tailwind CSS"
  | "Node.js"
  | "Express"
  | "Nodemon"
  | "CORS"
  | "PHP"
  | "Python"
  | "Pygame"
  | "PyTMX"
  | "PyScroll"
  | "FastAPI"
  | "Ollama"
  | "Java"
  | "JavaFX"
  | "Gradle"
  | "SQL"
  | "MySQL"
  | "NoSQL"
  | "Git / Github"
  | "Docker"
  | "Linux"
  | "Three.js"
  | "Xampp"
  | "Unity"
  | "C#"
  | "Jira"
  | "Cloudflare"
  | "Railway"
  | "KV Namespace"
  | "Minecraft Forge"
  | "Batch"
  | "Flutter"
  | "WMS (Warehouse Management System)"
  | "TMS (Transport Management System)"
  | "PLC Programming"
  | "SCADA Systems"
  | "ERP Systems"
  | "Industrial Robotics Basics"
  | "AI Industrial Basics"
  | "OSPF"
  | "VLANs"
  | "STP"
  | "DHCP"
  | "NAT"
  | "DNS"
  | "VPN"
  | "IPv4 / IPv6"
  | "TCP/IP"
  | "AWS"
  | "Azure"